# Generated by Django 5.2.4 on 2025-07-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="укажите название услуги",
                        max_length=200,
                        verbose_name="название услуги",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="описание услуги"
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="укажите цену на услугу",
                        null=True,
                        verbose_name="цена",
                    ),
                ),
            ],
            options={
                "verbose_name": "услуга",
                "verbose_name_plural": "услуги",
            },
        ),
    ]
