# Generated by Django 5.2.4 on 2025-07-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="services/photo/",
                verbose_name="Фото услуг",
            ),
        ),
    ]
