# Generated by Django 5.2.4 on 2025-07-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("doctor of functional diagnostics", "Функциональная диагностика"),
                    ("Radiation diagnostics", "Лучевая диагностика"),
                    (
                        "A doctor of ultrasound diagnostics",
                        "Ультразвуковая диагностика",
                    ),
                    (
                        "Doctor of clinical laboratory diagnostics",
                        "Клиническая лабораторная диагностика",
                    ),
                ],
                default="Функциональная диагностика",
                max_length=250,
                verbose_name="вид диагностической услуги",
            ),
        ),
    ]
