# Generated by Django 5.2.4 on 2025-07-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_service_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("Functional diagnostics", "Функциональная диагностика"),
                    ("Radiation diagnostics", "Лучевая диагностика"),
                    ("Ultrasound diagnostics", "Ультразвуковая диагностика"),
                    (
                        "Clinical laboratory diagnostics",
                        "Клиническая лабораторная диагностика",
                    ),
                ],
                default="Функциональная диагностика",
                max_length=250,
                verbose_name="вид диагностической услуги",
            ),
        ),
    ]
