# Generated by Django 5.2.4 on 2025-07-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_service_specialization"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="specialization",
            new_name="service_specialization",
        ),
    ]
