# Generated by Django 5.2.4 on 2025-07-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=100, verbose_name="Имя и фамилия доктора"
                    ),
                ),
                (
                    "work_experience",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="стаж работы"
                    ),
                ),
                ("resume", models.TextField(verbose_name="Резюме доктора")),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            (
                                "doctor of functional diagnostics",
                                "Врач функциональной диагностики",
                            ),
                            ("Radiation diagnostics", "Лучевой диагност"),
                            (
                                "A doctor of ultrasound diagnostics",
                                "Врач ультразвуковой диагностики",
                            ),
                            (
                                "Doctor of clinical laboratory diagnostics",
                                "Врач клинической лабораторной диагностики",
                            ),
                            (
                                "Doctor of the Centers of Hygiene and Epidemiology",
                                "Врач центров гигиены и эпидемиологии",
                            ),
                        ],
                        db_index=True,
                        max_length=150,
                        verbose_name="специализация",
                    ),
                ),
            ],
            options={
                "verbose_name": "доктор",
                "verbose_name_plural": "доктора",
            },
        ),
    ]
