# Generated by Django 5.2.4 on 2025-07-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="medicine/avatars/",
                verbose_name="Аватарка",
            ),
        ),
    ]
