# Generated by Django 5.2.4 on 2025-07-29 13:54

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0002_doctor_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название компании"),
                ),
                ("history", models.TextField(verbose_name="История компании")),
                (
                    "mission",
                    models.CharField(max_length=500, verbose_name="Миссия компания"),
                ),
                ("values", models.TextField(verbose_name="ценность компании")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
            ],
        ),
    ]
