# Generated by Django 5.2.4 on 2025-07-29 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0003_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="medicine.doctor",
                verbose_name="Врач",
            ),
        ),
    ]
