# Generated by Django 5.2.4 on 2025-07-30 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0004_company_doctor"),
        ("services", "0002_service_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Компания", "verbose_name_plural": "Компаний"},
        ),
        migrations.AddField(
            model_name="company",
            name="services",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.service",
                verbose_name="Услуги",
            ),
        ),
    ]
