# Generated by Django 5.2.4 on 2025-07-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0005_alter_company_options_company_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(
                choices=[
                    (
                        "doctor of functional diagnostics",
                        "Врач функциональной диагностики",
                    ),
                    ("Radiation diagnostics", "Лучевой диагност"),
                    (
                        "A doctor of ultrasound diagnostics",
                        "Врач ультразвуковой диагностики",
                    ),
                    (
                        "Doctor of clinical laboratory diagnostics",
                        "Врач клинической лабораторной диагностики",
                    ),
                ],
                db_index=True,
                max_length=150,
                verbose_name="специализация",
            ),
        ),
    ]
