# Generated by Django 5.2.4 on 2025-07-30 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0006_alter_doctor_specialization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_time",
                    models.DateTimeField(
                        help_text="укажите время записи на прием",
                        verbose_name="Запись на прием",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        help_text="укажите доктора к которому хотите записаться",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicine.doctor",
                        verbose_name="доктор",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на прием",
                "verbose_name_plural": "Записи на прием",
            },
        ),
    ]
