# Generated by Django 5.2.4 on 2025-07-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0007_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("You have an appointment", "Вы записаны на прием"),
                    ("You haven't made an appointment", "Вы не записаны на прием"),
                ],
                db_index=True,
                default="You haven't made an appointment",
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_time",
            field=models.DateTimeField(
                help_text="укажите время записи на прием", verbose_name="время"
            ),
        ),
    ]
