# Generated by Django 5.2.4 on 2025-07-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0008_appointment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("You have an appointment", "Вы записаны на прием"),
                    ("You haven't made an appointment", "Вы не записаны на прием"),
                ],
                db_index=True,
                default="Вы записаны на прием",
                verbose_name="Статус",
            ),
        ),
    ]
