# Generated by Django 5.2.4 on 2025-07-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0009_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="response",
            field=models.TextField(
                blank=True, null=True, verbose_name="Результаты диагностики"
            ),
        ),
    ]
