# Generated by Django 5.2.4 on 2025-07-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0011_company_email_alter_company_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="укажите адрес компании",
                max_length=400,
                null=True,
                verbose_name="адрес",
            ),
        ),
    ]
