# Generated by Django 5.2.4 on 2025-07-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0012_company_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="medicine/company/",
                verbose_name="Аватарка",
            ),
        ),
    ]
